{"name": "testcase2", "status": "failed", "statusDetails": {"message": "AssertionError: 2 != 3", "trace": "self = <UnitTestPython.UnitTest12345.CodeVlidation testMethod=testcase2>\n\n    def testcase2(self):\n        print(\"running the test case2\")\n>       self.assertEqual(2, 3)\nE       AssertionError: 2 != 3\n\nUnitTest12345.py:32: AssertionError"}, "attachments": [{"name": "stdout", "source": "9db9d881-1942-4615-b84a-4173347d213a-attachment.txt", "type": "text/plain"}], "start": 1587985380734, "stop": 1587985380734, "uuid": "065fef3b-2334-453b-bf1b-2869031148df", "historyId": "f3141be1c26339e1cf9338e265207956", "testCaseId": "aed9f78bcb6195e11cd8d29a6a2f317a", "fullName": "UnitTest12345.CodeVlidation#testcase2", "labels": [{"name": "feature", "value": "Your Feature here"}, {"name": "story", "value": "Your Story here"}, {"name": "suite", "value": "UnitTest12345"}, {"name": "subSuite", "value": "CodeVlidation"}, {"name": "host", "value": "DESKTOP-3A2H5GC"}, {"name": "thread", "value": "15292-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "UnitTest12345"}]}