{"name": "testcase2", "status": "failed", "statusDetails": {"message": "AssertionError: 2 != 3", "trace": "self = <UnitTestPython.UnitTest12345.CodeVlidation testMethod=testcase2>\n\n    def testcase2(self):\n        print(\"running the test case2\")\n>       self.assertEqual(2, 3)\nE       AssertionError: 2 != 3\n\nUnitTest12345.py:31: AssertionError"}, "attachments": [{"name": "stdout", "source": "93e0aa16-8293-4fd3-befe-8d1fc23029bf-attachment.txt", "type": "text/plain"}], "start": 1587985060594, "stop": 1587985060594, "uuid": "2401de99-1b6b-4fe9-94fe-160902db24c1", "historyId": "f3141be1c26339e1cf9338e265207956", "testCaseId": "aed9f78bcb6195e11cd8d29a6a2f317a", "fullName": "UnitTest12345.CodeVlidation#testcase2", "labels": [{"name": "story", "value": "Your Story here"}, {"name": "feature", "value": "Your Feature here"}, {"name": "suite", "value": "UnitTest12345"}, {"name": "subSuite", "value": "CodeVlidation"}, {"name": "host", "value": "DESKTOP-3A2H5GC"}, {"name": "thread", "value": "10832-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "UnitTest12345"}]}