{"name": "testcase2", "status": "failed", "statusDetails": {"message": "AssertionError: 2 != 3", "trace": "self = <UnitTestPython.UnitTest12345.CodeVlidation testMethod=testcase2>\n\n    def testcase2(self):\n        print(\"running the test case2\")\n>       self.assertEqual(2, 3)\nE       AssertionError: 2 != 3\n\nUnitTest12345.py:29: AssertionError"}, "attachments": [{"name": "stdout", "source": "99172257-2711-49f2-b8df-cde065a36380-attachment.txt", "type": "text/plain"}], "start": 1587984477618, "stop": 1587984477618, "uuid": "11fea94f-5ffe-4f09-9bbc-c11ef492b4c7", "historyId": "f3141be1c26339e1cf9338e265207956", "testCaseId": "aed9f78bcb6195e11cd8d29a6a2f317a", "fullName": "UnitTest12345.CodeVlidation#testcase2", "labels": [{"name": "suite", "value": "UnitTest12345"}, {"name": "subSuite", "value": "CodeVlidation"}, {"name": "host", "value": "DESKTOP-3A2H5GC"}, {"name": "thread", "value": "2612-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "UnitTest12345"}]}