{"name": "testcase2", "status": "failed", "statusDetails": {"message": "AssertionError: 2 != 3", "trace": "self = <UnitTestPython.UnitTest12345.CodeVlidation testMethod=testcase2>\n\n    def testcase2(self):\n        print(\"running the test case2\")\n>       self.assertEqual(2, 3)\nE       AssertionError: 2 != 3\n\nUnitTest12345.py:29: AssertionError"}, "attachments": [{"name": "stdout", "source": "550d9ba6-b043-4551-820f-f5502f68e9a4-attachment.txt", "type": "text/plain"}], "start": 1587984462662, "stop": 1587984462662, "uuid": "b15688e4-b62c-4983-a336-2647ae631eed", "historyId": "f3141be1c26339e1cf9338e265207956", "testCaseId": "aed9f78bcb6195e11cd8d29a6a2f317a", "fullName": "UnitTest12345.CodeVlidation#testcase2", "labels": [{"name": "suite", "value": "UnitTest12345"}, {"name": "subSuite", "value": "CodeVlidation"}, {"name": "host", "value": "DESKTOP-3A2H5GC"}, {"name": "thread", "value": "13936-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "UnitTest12345"}]}